### ISSUE TITLE
[minor] availability via homebrew

### ISSUE THREAD

**Issue by aegershman** [get-ytt/ytt#5]
In order to make `ytt` accessible via [`homebrew`](https://github.com/Homebrew) package management, it would be nice if the `ytt` binary were made available in a brew repository.

/cc @drnic I don't mean to be presumptive of `starkandwayne`'s ci/cd process for binaries like this, but maybe this is something you all might consider adding into one of the `homebrew-*` repository lineups.

**Comment by cppforlife** [comment]
created: https://github.com/get-ytt/homebrew-tap
